version: '2'
services:
    ground-app:
        image: ground
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ground-mysql:3306/ground?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=ground-elasticsearch:9300
        ports:
            - 8080:8080
    ground-mysql:
        extends:
            file: mysql.yml
            service: ground-mysql
    ground-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ground-elasticsearch
